/* ===== Build 3 · financial profile: what you have, what you owe, assets, wellness score ===== */
TITLES.profile='My money profile';
const ASSET_TYPES={land:['Land','map'],house:['House or building','house'],vehicle:['Vehicle or boda','bike'],livestock:['Livestock','people'],business:['Business or stock','bag'],equipment:['Equipment','gear'],jewellery:['Jewellery','sparkle'],other:['Other','dots']};
function monthly(kind){const span=60;const since=plusDays(TODAY0,-span);const first=S.txns.length?Math.min(...S.txns.map(t=>pd(t.d).getTime())):Date.now();
 const days=Math.max(7,Math.min(span,(Date.now()-Math.max(first,since.getTime()))/DAY));const v=sumAmt(S.txns.filter(t=>t.kind===kind&&pd(t.d)>=since));return v/days*30.4}
const liquidNow=()=>S.accounts.filter(a=>['momo','bank','cash'].includes(a.kind)).reduce((s,a)=>s+inHome(a),0);
let savingsNow=()=>S.accounts.filter(a=>a.kind==='sacco').reduce((s,a)=>s+inHome(a),0);
let creditLeft=()=>S.accounts.reduce((s,a)=>s+(Math.max(0,(a.advLimit||0)-(a.advUsed||0))+Math.max(0,(a.loanLimit||0)-(a.loanOwed||0)))*acctRate(a),0);
function wellness(){const inc=monthly('in'),out=monthly('out');const debt=providerDebt()+loansTaken();
 if(!inc&&!out)return null;
 const sRate=inc?(inc-out)/inc:0;const save=Math.max(0,Math.min(25,sRate/.2*25));
 const cover=out?liquidNow()/out:0;const buffer=Math.max(0,Math.min(25,cover/3*25));
 const dti=inc?debt/inc:(debt?3:0);const debtS=Math.max(0,25-dti/3*25);
 const bud=S.cats.filter(c=>c.budget);const pace=DAY_OF_CYCLE/CYCLE_DAYS;const within=bud.filter(c=>catSpent(c.id)<=c.budget*Math.max(pace,.25)*1.15).length;const budS=bud.length?within/bud.length*25:12;
 return{score:Math.round(save+buffer+debtS+budS),parts:[['Saving',save,`You keep ${Math.round(sRate*100)}% of what comes in. Aim for 20%.`],['Safety buffer',buffer,`Money you can use covers ${cover.toFixed(1)} months of spending. Aim for 3.`],['Debt',debtS,debt?`What you owe equals ${(dti).toFixed(1)} months of income.`:'You owe nothing. Well done.'],['Budget',budS,bud.length?`${within} of ${bud.length} categories are within pace.`:'Set budget limits to score this.']],inc,out,cover,dti,sRate}}
const scoreWord=s=>s>=75?'Strong':s>=55?'Steady':s>=35?'Building':'Needs attention';
SCREENS.profile=()=>{const u=S.user||{};const cty=country();const w=wellness();const g=S.game||{};
 const liquid=liquidNow(),sav=savingsNow(),inv=invTotal(),owed=owedToMe(),assets=assetTotal();
 const adv=S.accounts.reduce((s,a)=>s+(a.advUsed||0)*acctRate(a),0),ploans=S.accounts.reduce((s,a)=>s+(a.loanOwed||0)*acctRate(a),0),people=loansTaken();
 const have=liquid+sav+inv+owed+assets,oweT=adv+ploans+people;
 const line=(l,v,cls,sub)=>`<div class="setrow" style="padding:10px 14px"><span class="grow"><b style="font-size:14px">${l}</b>${sub?`<span>${sub}</span>`:''}</span><span class="tnum ${cls||''}" style="font-weight:700">${ugx(v)}</span></div>`;
 return `
 <div class="card row" style="gap:14px"><span class="avatar" style="width:56px;height:56px;font-size:19px">${initials(u.name)}</span><div class="grow"><b style="font-size:18px">${esc(u.full||u.name||'You')}</b><div class="small muted">${esc(cty[1])} · ${CUR()}${S.household?' · '+esc(S.household.name):''}</div>${g.streak?`<span class="pill sun" style="margin-top:6px">${ic('bolt',12)} ${g.streak}-day streak</span>`:''}</div><button class="btn sm" data-act="editProfile">Edit</button></div>
 ${w?`<div class="card row" style="gap:16px;align-items:center">${ring(w.score/100,112,11,w.score>=55?'var(--good)':w.score>=35?'var(--warn)':'var(--bad)',w.score,'of 100')}<div class="grow stack" style="gap:6px"><span class="eyebrow">Financial wellness</span><b style="font-size:18px">${scoreWord(w.score)}</b>${w.parts.map(([n,v])=>`<div class="stack" style="gap:2px"><div class="between xs"><span>${n}</span><span class="muted">${Math.round(v)}/25</span></div><div class="bar" style="height:5px"><i style="width:${v/25*100}%"></i></div></div>`).join('')}</div></div>
 <details class="card" style="padding:12px 16px"><summary class="small" style="cursor:pointer;font-weight:600">What the score means</summary><div class="stack small" style="gap:6px;margin-top:8px">${w.parts.map(([n,,t])=>`<p><b>${n}:</b> ${t}</p>`).join('')}<p class="xs muted">Worked out from the last 60 days on this phone. It's a guide, not a credit score.</p></div></details>`
 :`<div class="note">${ic('info')}<span class="small">Your wellness score appears once you have a few weeks of income and spending logged.</span></div>`}
 <div class="card" style="padding:16px;background:linear-gradient(150deg,var(--hero),var(--hero-2));color:var(--hero-ink);border:0"><span class="eyebrow" style="color:var(--hero-muted)">Net worth</span><div class="tnum" style="font-family:var(--f-display);font-weight:800;font-size:30px;margin-top:4px">${ugx(have-oweT)}</div><div class="small" style="color:var(--hero-muted)">You have ${ugx(have)} and owe ${ugx(oweT)}</div></div>
 <div class="kpi"><div class="stat"><span>Months of cover</span><b>${w&&w.out?(liquid/w.out).toFixed(1):'—'}</b></div><div class="stat"><span>Credit available</span><b>${kf(creditLeft())}</b></div><div class="stat"><span>Spend per month</span><b>${w?kf(w.out):'—'}</b></div><div class="stat"><span>Income per month</span><b>${w?kf(w.inc):'—'}</b></div></div>
 <div class="sec-head"><h2>What you have</h2><b class="tnum small">${ugx(have)}</b></div>
 <div class="list">${line('Money you can use',liquid,'','Mobile money, bank and cash')}${sav?line('Savings',sav,'','SACCO, MoKash and group savings'):''}${line('Investments',inv,'',S.inv.length?S.inv.length+' holding'+(S.inv.length>1?'s':''):'None yet')}${owed?line('Money people owe you',owed):''}${line('Property and other assets',assets,'',(S.assets||[]).length?(S.assets.length+' item'+(S.assets.length>1?'s':'')):'Land, a house, a vehicle, livestock…')}</div>
 <div class="sec-head"><h2>What you owe</h2><b class="tnum small liab">${ugx(oweT)}</b></div>
 <div class="list">${oweT?`${adv?line('Mobile money advances',adv,'liab','MoMo Advance, Fuliza and similar'):''}${ploans?line('Loans from providers',ploans,'liab','MoKash, bank and app loans'):''}${people?line('Money borrowed from people',people,'liab'):''}`:'<div class="setrow"><span class="grow"><b>Nothing owed</b><span>Advances and loans show here when you take them</span></span></div>'}</div>
 <div class="sec-head"><h2>Accounts</h2><button class="link" data-go="accounts">Manage</button></div>
 <div class="list">${S.accounts.map(a=>`<button class="tx" data-act="acct" data-arg="${a.id}">${acctBadge(a,36)}<span class="tx-main"><span class="tx-title">${esc(a.name)}</span><span class="tx-sub">${esc(KIND_LABEL[a.kind]||'')}${a.loanOwed?` · <span class="liab">loan ${fmtNum(a.loanOwed,a.currency)}</span>`:''}${advLine(a)?` · <span class="${a.advUsed?'liab':''}">${advLine(a)}</span>`:''}</span></span><span class="tx-amt ${acctReads(a)<0?'liab':''}">${signedNum(acctReads(a),a.currency)}${a.currency!==CUR()?`<small>${a.currency}</small>`:''}</span></button>`).join('')}</div>
 <div class="sec-head"><h2>Property and assets</h2><button class="link" data-act="addAsset">Add</button></div>
 ${(S.assets||[]).length?`<div class="list">${S.assets.map(x=>{const t=ASSET_TYPES[x.type]||ASSET_TYPES.other;return `<button class="tx" data-act="editAsset" data-arg="${x.id}"><span class="chip" style="--c:var(--accent)">${ic(t[1])}</span><span class="tx-main"><span class="tx-title">${esc(x.name)}</span><span class="tx-sub">${t[0]}${x.note?' · '+esc(x.note):''}</span></span><span class="tx-amt">${kf(+x.value||0)}</span></button>`}).join('')}</div>`:`<button class="card" data-act="addAsset" style="text-align:left"><b>Add what you own</b><p class="small muted" style="margin-top:4px">Land, a house, a car or boda, livestock or business stock. Use a fair price you could sell it for today.</p></button>`}
 <div class="sec-head"><h2>Spending habits</h2><button class="link" data-go="spending">Details</button></div>
 <div class="card stack" style="gap:8px">${(()=>{const l=S.txns.filter(t=>t.kind==='out'&&pd(t.d)>=plusDays(TODAY0,-60));const tot=sumAmt(l);if(!tot)return '<p class="small muted">Log a few weeks of spending to see your habits.</p>';return groupSum(l,t=>t.cat).slice(0,4).map(([id,v])=>`<div class="stack" style="gap:3px"><div class="between small"><span>${(cat(id)||{}).name||id}</span><span class="tnum">${Math.round(v/tot*100)}%</span></div><div class="bar" style="height:6px"><i style="width:${v/tot*100}%;background:${(cat(id)||{}).c||'var(--accent)'}"></i></div></div>`).join('')+`<p class="xs muted">Last 60 days · ${ugx(tot)} in total</p>`})()}</div>
 <button class="btn block" data-act="askReview">${ic('sparkle')}Get advice based on my profile</button>`};
const assetForm=x=>{const isNew=!x;x=x||{type:'land',name:'',value:'',note:''};return `<form class="stack" data-form="asset" ${isNew?'':`data-id="${x.id}"`}><label class="field"><span>Type</span><select name="type">${Object.entries(ASSET_TYPES).map(([k,v])=>`<option value="${k}" ${k===x.type?'selected':''}>${v[0]}</option>`).join('')}</select></label><label class="field"><span>Name</span><input name="name" value="${esc(x.name)}" placeholder="e.g. Plot in Mukono" required></label><label class="field"><span>Value today (${CUR()})</span><input name="value" type="number" inputmode="decimal" step="any" value="${x.value}" required></label><label class="field"><span>Note (optional)</span><input name="note" value="${esc(x.note||'')}" placeholder="Size, title, income it earns…"></label><button class="btn primary">${isNew?'Add':'Save'}</button>${isNew?'':`<button type="button" class="btn danger" data-act="delAsset" data-arg="${x.id}">Remove</button>`}</form>`};
ACT.addAsset=()=>openSheet('Add an asset',assetForm(null));
ACT.editAsset=id=>openSheet('Edit asset',assetForm(S.assets.find(x=>x.id===id)));
FORMS.asset=(fd,f)=>{const v={type:fd.get('type'),name:fd.get('name').trim(),value:+fd.get('value')||0,note:fd.get('note').trim()};if(f.dataset.id)Object.assign(S.assets.find(x=>x.id===f.dataset.id),v);else S.assets.push({id:nid('as'),...v});closeSheet();refresh();toast('Saved');if(window.gameBadge)gameBadge('assets')};
ACT.delAsset=id=>{S.assets=S.assets.filter(x=>x.id!==id);closeSheet();refresh()};
