/* ===== Build 3 · Advisor: Ask, Learn, My review ===== */
const LESSONS=[
 {id:'budget',t:'Budgeting when income changes every month',ic:'chart',min:3,b:`<p>Many people in Africa earn irregular money: business sales, contracts, tips, harvests. A fixed monthly budget breaks the first time a slow month comes. Budget from your lowest normal month instead.</p><ul><li><b>Find your floor.</b> Look at the last three to six months and take the lowest income. That is what you plan your must-pay costs around: rent, food, school fees, transport, utilities.</li><li><b>Pay the essentials first.</b> When money arrives, cover the essentials before anything else.</li><li><b>Split the extra.</b> Anything above the floor gets divided, for example half to savings or debt, half to wants.</li><li><b>Keep a buffer account.</b> Good months top it up, slow months draw from it, so your spending stays steady.</li></ul><p>Kasente helps by setting limits per category and showing the even-pace line on your budget.</p>`},
 {id:'buffer',t:'Your emergency fund',ic:'shield',min:3,b:`<p>An emergency fund is money set aside only for surprises: a hospital bill, a lost job, a funeral contribution, a broken phone. Without one, surprises become debt.</p><ul><li><b>First target:</b> one month of essential spending.</li><li><b>Full target:</b> three to six months.</li><li><b>Keep it separate</b> from everyday money so it doesn't get spent. A SACCO savings account, a money market fund or a separate bank account works. Avoid locking it where you can't reach it within a few days.</li><li><b>Start small.</b> Even 5% of each payment, moved the day it arrives, adds up.</li></ul><p>Your profile shows how many months of cover you have right now.</p>`},
 {id:'mobile-credit',t:'The real cost of mobile advances and app loans',ic:'hand',min:4,b:`<p>MoMo Advance, Fuliza, MoKash, Wewole and app loans are fast, but their fees are high when you look at them over a year.</p><ul><li>A fee of 10% for a 30-day loan adds up to more than 100% a year if you keep borrowing like that.</li><li>Daily fees on overdraft-style advances add up quietly. Check the fee schedule in your provider's menu.</li><li>Late repayment can be reported to credit reference bureaus and make future borrowing harder or more expensive.</li></ul><p><b>Use them for true emergencies, not regular spending.</b> If you find yourself borrowing every month before payday, your budget is short by about that amount. Fix the budget or build a small buffer, then stop the cycle.</p><p>Kasente tracks advances on each account so you can see what you owe and what the next payment into your wallet will recover.</p>`},
 {id:'debt',t:'Getting out of debt',ic:'trend',min:3,b:`<p>List everything you owe: who, how much, the fee or interest, and the due date. Then choose a method.</p><ul><li><b>Avalanche:</b> pay the minimum on everything and put every extra shilling on the debt with the highest cost. This saves the most money.</li><li><b>Snowball:</b> pay off the smallest debt first, then roll that payment into the next. The quick wins keep you motivated.</li></ul><p>Either works if you stick to it. Talk to lenders early if you can't pay; many will agree a plan before the debt goes to collection. Don't take a new loan to pay an old one unless it clearly costs less.</p>`},
 {id:'sacco',t:'SACCOs and savings groups',ic:'coins',min:3,b:`<p>A SACCO is a savings and credit co-operative owned by its members. Savings groups (VSLAs, chamas, ekibiina) work in a similar spirit with a smaller circle of people.</p><ul><li><b>Good for:</b> saving regularly, borrowing at fair member rates, and sometimes earning a yearly dividend on shares.</li><li><b>Before joining a SACCO:</b> check that it is registered and regulated, ask for the latest audited accounts, and find out how long withdrawals take.</li><li><b>In a group:</b> agree written rules on contributions, loans, interest and what happens if someone leaves or doesn't pay.</li></ul><p>Record SACCO and group savings as accounts in Kasente so they count in your net worth.</p>`},
 {id:'tbills',t:'Treasury bills and bonds',ic:'calendar',min:3,b:`<p>Treasury bills and bonds are loans you make to your government. They are among the safest places for money you won't need for a while.</p><ul><li><b>Bills</b> are short term (in Uganda: 91, 182 and 364 days). You pay less than the face value and receive the full amount at the end.</li><li><b>Bonds</b> are longer (2 to 20 years) and pay interest twice a year.</li><li>Rates are set at regular auctions run by the central bank. Interest is taxed, so compare after-tax returns.</li><li>You can usually buy through the central bank's online platform, a commercial bank, or a licensed broker.</li></ul><p>Selling a bond before it matures depends on finding a buyer at the going price, so match the term to when you'll need the money.</p>`},
 {id:'unit',t:'Unit trusts and money market funds',ic:'chart',min:3,b:`<p>A unit trust pools money from many people and is run by a licensed fund manager. You own units whose value moves with the fund.</p><ul><li><b>Money market funds</b> invest in short-term deposits and government bills. They are steady and you can usually withdraw within a few days, so they suit emergency funds and short goals.</li><li><b>Balanced and equity funds</b> include company shares. They can grow more over years but also fall.</li><li>Check the manager is licensed by the capital markets regulator, and look at the fees and past returns, not just adverts.</li></ul><p>Apps such as Xeno in Uganda make regular small contributions easy. Kasente can record their confirmation messages under Investments.</p>`},
 {id:'retire',t:'Planning for retirement',ic:'house',min:3,b:`<p>Retirement feels far away, but small amounts started early grow the most.</p><ul><li><b>In Uganda,</b> formal employees contribute to NSSF: the employer pays 10% of salary and the employee 5%. Check your statement regularly to make sure contributions are arriving.</li><li><b>Voluntary saving</b> on top of NSSF, through a pension plan, unit trust or bonds, fills the gap, especially for self-employed people.</li><li><b>Avoid using retirement money early.</b> It's the hardest money to replace.</li></ul>`},
 {id:'scams',t:'Staying safe from money scams',ic:'shield',min:3,b:`<p>Scammers target mobile money users every day. The common tricks:</p><ul><li><b>"I sent money to you by mistake, please send it back."</b> Check your actual balance in the official menu, not the SMS. Fake SMS messages look real.</li><li><b>Calls from "customer care"</b> asking for your PIN or a code. No real provider ever asks for your PIN.</li><li><b>Prizes and promotions</b> that ask you to pay a fee or dial a code to claim.</li><li><b>Investment schemes</b> promising very high, guaranteed returns or paying you for bringing in new members.</li></ul><p>Never share your PIN or one-time codes. If in doubt, hang up and call the provider's official number yourself.</p>`},
 {id:'family',t:'Supporting family without going broke',ic:'people',min:3,b:`<p>Supporting parents, siblings and relatives is part of life for many people. It works best when it's planned, not reactive.</p><ul><li><b>Set a monthly family-support amount</b> in your budget and stick to it.</li><li><b>Be open with your household</b> about what you can give, so requests don't become surprises.</li><li><b>Help in ways that last:</b> school fees paid directly to the school, or start-up help for a small business, rather than repeated cash.</li><li><b>Keep your own safety buffer first.</b> You can't help anyone if you fall into debt.</li></ul><p>Kasente's Family category and household mode show exactly how much goes to supporting others.</p>`},
 {id:'health',t:'Health costs and insurance',ic:'cross',min:3,b:`<p>Health spending is one of the biggest reasons households fall into debt.</p><ul><li><b>Track it:</b> pharmacy, clinic, lab tests, dental and eye care. Kasente groups them under Health.</li><li><b>Compare insurance with what you actually spend.</b> If a family member needs regular care, a plan may cost less than paying each visit.</li><li><b>Read what a plan covers:</b> outpatient or only inpatient, which hospitals, waiting periods, and limits.</li><li><b>Keep part of your emergency fund</b> for health surprises.</li></ul>`},
 {id:'fees',t:'Planning for school fees',ic:'book',min:2,b:`<p>School fees arrive at the same times every year, so they shouldn't be a surprise.</p><ul><li>Divide each term's fees by the months until it's due, and save that amount every month in a separate goal.</li><li>Ask the school about paying in instalments.</li><li>Uniforms, books and transport add more on top of tuition. Include them in your goal.</li></ul><p>Create a savings goal in Kasente for each term and it will tell you if you're on track.</p>`},
 {id:'business',t:'Keep business and personal money apart',ic:'bag',min:2,b:`<p>Mixing business takings with household money is the fastest way to lose track of whether a business is making a profit.</p><ul><li>Use a separate mobile money line or account for the business.</li><li>Pay yourself a fixed amount from the business each week or month, like a salary.</li><li>Record stock purchases and sales, even roughly.</li></ul><p>In Kasente, add the business wallet as its own account and use the Business category for its costs.</p>`}];
const BOOKS=[
 ['The Richest Man in Babylon','George S. Clason','Short, simple rules about saving a part of everything you earn. A classic place to start.'],
 ['The Psychology of Money','Morgan Housel','Why behaviour matters more than knowledge when it comes to money.'],
 ['Poor Economics','Abhijit V. Banerjee & Esther Duflo','How families on low incomes actually save, borrow and decide. Many examples from Africa.'],
 ['Portfolios of the Poor','Daryl Collins, Jonathan Morduch, Stuart Rutherford & Orlanda Ruthven','Year-long money diaries, including South African households, showing how people juggle irregular income.'],
 ['Black Tax: Burden or Ubuntu?','Edited by Niq Mhlongo','South African writers on supporting extended family financially.'],
 ['The Millionaire Next Door','Thomas J. Stanley & William D. Danko','How ordinary people build wealth by spending less than they earn.'],
 ['I Will Teach You to Be Rich','Ramit Sethi','Automating savings and spending without guilt on the things you value.'],
 ['Your Money or Your Life','Vicki Robin & Joe Dominguez','Seeing spending as hours of your life, and deciding what is worth it.'],
 ['Rich Dad Poor Dad','Robert T. Kiyosaki','Popular for its ideas about assets and income. Treat the investing advice with caution.']];
const RESOURCES=[['Bank of Uganda','Financial literacy and Treasury bill information','https://www.bou.or.ug'],['Capital Markets Authority (Uganda)','Investor education and licensed fund managers','https://www.cmauganda.co.ug'],['NSSF Uganda','Check your retirement savings','https://www.nssfug.org'],['Central Bank of Kenya','Treasury bills, bonds and consumer protection','https://www.centralbank.go.ke'],['Capital Markets Authority (Kenya)','Investor education and licensed firms','https://www.cma.or.ke'],['Bank of Tanzania','Government securities and financial education','https://www.bot.go.tz']];

/* ---------- anonymised summary (what the Claude advisor would see) ---------- */
function financeSummary(){const since=plusDays(TODAY0,-60);const l=S.txns.filter(t=>pd(t.d)>=since);const out=l.filter(t=>t.kind==='out');const w=wellness();
 return{country:country()[1],currency:CUR(),pay_cycle:`${ymd(CYCLE_START)} to ${ymd(CYCLE_END)}`,day_of_cycle:DAY_OF_CYCLE,
  monthly_income_est:Math.round(monthly('in')),monthly_spending_est:Math.round(monthly('out')),
  spending_last_60_days_by_category:Object.fromEntries(groupSum(out,t=>(cat(t.cat)||{}).name||t.cat)),
  biggest_subcategories:Object.fromEntries(groupSum(out,t=>subOf(t)||'unspecified').slice(0,8)),
  fees_last_60_days:sumAmt(out.filter(t=>t.sub==='Mobile money & bank fees')),
  this_cycle_budget:{total:totalBudget(),spent:cycleSpent(),over:S.cats.filter(c=>c.budget&&catSpent(c.id)>c.budget).map(c=>c.name)},
  money_available_now:Math.round(liquidNow()),savings:Math.round(savingsNow()),investments:Math.round(invTotal()),assets:Math.round(assetTotal()),
  owed_to_providers:Math.round(providerDebt()),borrowed_from_people:Math.round(loansTaken()),owed_by_people:Math.round(owedToMe()),
  advances_used_last_60_days:l.filter(t=>t.kind==='borrow').length,
  goals:S.goals.map(g=>({target:g.target,saved:g.saved,due:g.date})),household_members:S.household?S.household.members.length:1,
  wellness_score:w?w.score:null}}
const AI_SYSTEM=()=>`You are Kasente's money coach for everyday people in ${country()[1]} and across Africa. You receive an anonymised summary of the person's finances (no names or transactions) and a question. Answer in plain, warm, practical language a busy person can act on today. Use ${CUR()} for amounts. Refer to local realities where useful: mobile money, SACCOs, savings groups, Treasury bills, NSSF, school fees, supporting family. Keep it under 220 words. Use short paragraphs or "- " bullets, no headings, no markdown tables. Never ask for PINs or account numbers. This is general education, not regulated financial advice; say so in one short line only if recommending an investment.`;
const aiOn=()=>{try{return !!(NATIVE&&NATIVE.hasAiKey&&NATIVE.hasAiKey()&&S.settings.useClaude!==false)}catch(e){return false}};
function aiAsk(q){return new Promise(res=>{const id='ai'+Date.now().toString(36);cloudWait[id]=res;try{NATIVE.aiAsk(AI_SYSTEM(),`My finances (anonymised):\n${JSON.stringify(financeSummary())}\n\nMy question: ${q}`,id)}catch(e){delete cloudWait[id];res({ok:false,status:0,text:String(e)})}setTimeout(()=>{if(cloudWait[id]){delete cloudWait[id];res({ok:false,status:0,text:'timeout'})}},100000)})}
const mdLite=t=>{const lines=esc(t).replace(/\*\*(.+?)\*\*/g,'<b>$1</b>').split('\n');let html='',inList=false;lines.forEach(l=>{const m=l.match(/^\s*[-•*]\s+(.*)/);if(m){if(!inList){html+='<ul>';inList=true}html+=`<li>${m[1]}</li>`}else{if(inList){html+='</ul>';inList=false}if(l.trim())html+=`<p style="margin:0 0 6px">${l}</p>`}});if(inList)html+='</ul>';return html};

/* ---------- personal review from your own history ---------- */
function reviewItems(){const out=[];const w=wellness();const since=plusDays(TODAY0,-60);const l60=S.txns.filter(t=>pd(t.d)>=since);
 if(!S.txns.filter(t=>t.kind==='out').length)return[{t:'Log a week of spending first',b:'Your review is built from what you actually spend. Log your expenses for a week, or let Kasente read your MoMo messages, and come back.',a:['add','Log an expense'],k:'info'}];
 if(w&&w.out){const cover=liquidNow()/w.out;if(cover<1)out.push({t:'Build a safety buffer',b:`Money you can use covers ${cover.toFixed(1)} months of spending. A first target of one month is about ${ugx(Math.round(w.out/1000)*1000)}. Moving 5–10% of every payment into a separate goal gets you there.`,a:['goalBuffer','Create a buffer goal'],k:'warn'});else if(cover<3)out.push({t:'Keep growing your buffer',b:`You have ${cover.toFixed(1)} months of cover. Three months, about ${ugx(Math.round(w.out*3/1000)*1000)}, protects you from most surprises.`,a:['goalBuffer','Create a buffer goal'],k:'accent'})}
 if(w&&w.inc&&w.sRate<.1)out.push({t:w.sRate<0?'You are spending more than you earn':'Save a little more of each payment',b:w.sRate<0?`Recent spending is about ${ugx(Math.round((w.out-w.inc)/1000)*1000)} a month more than income. Look at the biggest categories in Spending and pick one to cut first.`:`You keep about ${Math.round(w.sRate*100)}% of what comes in. Try moving 10% to savings the day money arrives, before spending starts.`,a:['go:spending','Open Spending'],k:'bad'});
 const adv=l60.filter(t=>t.kind==='borrow');const owe=providerDebt();if(adv.length>=2||owe)out.push({t:'Mobile advances and loans',b:`${adv.length?`You took ${adv.length} advance${adv.length>1?'s':''} or loan${adv.length>1?'s':''} in the last 60 days. `:''}${owe?`You owe providers ${ugx(owe)}. `:''}Regular borrowing before payday means your budget is short by about that amount. A small buffer breaks the cycle and saves the fees.`,a:['lesson:mobile-credit','Read: the real cost'],k:'warn'});
 const prevC=S.txns.filter(t=>t.kind==='out'&&pd(t.d)>=PREV_START&&pd(t.d)<CYCLE_START);if(prevC.length>5){const frac=Math.min(1,DAY_OF_CYCLE/CYCLE_DAYS);const grow=S.cats.map(c=>{const now=catSpent(c.id),then=sumAmt(prevC.filter(t=>t.cat===c.id))*frac;return{c,now,then,g:then?(now-then)/then:0}}).filter(x=>x.then>5000&&x.g>.2).sort((a,b)=>b.g-a.g)[0];
  if(grow)out.push({t:`${grow.c.name} is rising`,b:`You've spent ${ugx(grow.now)} on ${grow.c.name.toLowerCase()} so far this cycle, about ${Math.round(grow.g*100)}% more than at the same point last cycle.`,a:['spTx:'+grow.c.id,'See the payments'],k:'warn'})}
 const over=S.cats.filter(c=>c.budget&&catSpent(c.id)>c.budget);if(over.length)out.push({t:`Over budget: ${over.map(c=>c.name).join(', ')}`,b:'Either the limit is unrealistic or spending needs to come down. Adjust the limit to what you can really live on, then hold to it.',a:['go:budgets','Review budgets'],k:'bad'});
 if(!S.cats.some(c=>c.budget))out.push({t:'Set your budget limits',b:'Limits per category are what make alerts and pace tracking work.',a:['go:budgets','Set limits'],k:'accent'});
 const fees=sumAmt(l60.filter(t=>t.sub==='Mobile money & bank fees'));if(fees>0)out.push({t:`${ugx(fees)} spent on fees in 60 days`,b:'Sending fewer, larger amounts, paying merchants directly from your wallet, and avoiding cash withdrawals where possible all reduce fees.',a:['go:spending','See spending'],k:'accent'});
 const bet=sumAmt(l60.filter(t=>subOf(t)==='Betting & lottery'));if(bet)out.push({t:`${ugx(bet)} on betting in 60 days`,b:'If betting is entertainment, set a fixed monthly limit for it in your budget and stop when it is used.',a:['go:budgets','Set a limit'],k:'warn'});
 const health=sumAmt(l60.filter(t=>t.cat==='health'));if(health>50000&&!l60.some(t=>subOf(t)==='Health insurance'))out.push({t:'Compare health insurance',b:`You spent ${ugx(health)} on health in 60 days. Ask a few insurers what a plan would cost and compare.`,a:['lesson:health','Read: health costs'],k:'accent'});
 const late=S.loans.filter(l=>l.dir==='out'&&l.amt>l.paid&&daysUntil(l.due)<0);if(late.length)out.push({t:`${late.length} person${late.length>1?'s':''} owe${late.length>1?'':'s'} you past the agreed date`,b:`${ugx(late.reduce((s,l)=>s+l.amt-l.paid,0))} outstanding. A friendly reminder now is easier than later.`,a:['go:lending','Open lending'],k:'warn'});
 if(!S.goals.length)out.push({t:'Give your savings a purpose',b:'People save more when the money has a name: school fees, a phone, land. Create one goal to start.',a:['addGoal','Create a goal'],k:'accent'});
 const offPace=S.goals.filter(g=>g.rate<goalNeed(g)*.97);if(offPace.length)out.push({t:`${offPace.length} goal${offPace.length>1?'s are':' is'} behind`,b:offPace.map(g=>`${g.name}: about ${ugx(Math.round(goalNeed(g)/1000)*1000)} a month needed`).join('. ')+'.',a:['go:goals','Open goals'],k:'warn'});
 if(!out.length)out.push({t:'You are doing well',b:'No warning signs in your recent history. Keep logging, and consider moving extra money into investments for longer-term goals.',a:['go:invest','Explore investments'],k:'good'});
 return out}
ACT.goalBuffer=()=>{const w=wellness();openGoal(Math.round(((w&&w.out)||300000)/1000)*1000,ymd(plusDays(TODAY0,120)));setTimeout(()=>{const n=document.querySelector('[data-form=addGoal] [name=name]');if(n)n.value='Emergency fund'},50)};
ACT.revAct=a=>{if(a.startsWith('go:'))go(a.slice(3));else if(a.startsWith('lesson:')){S.ui.adv='learn';S.ui.lesson=a.slice(7);go('advisor')}else if(a.startsWith('spTx:')){S.ui.sp='cycle';go('spending');ACT.spTx(a.slice(5))}else if(ACT[a])ACT[a]()};
ACT.askReview=()=>{S.ui.adv='review';go('advisor')};

/* ---------- the Advisor screen ---------- */
SCREENS.advisor=()=>{const tab=S.ui.adv||'ask';
 const tabs=`<div class="tabbar">${[['ask','Ask'],['learn','Learn'],['review','My review']].map(([k,l])=>`<button class="${tab===k?'on':''}" data-act="advTab" data-arg="${k}">${l}</button>`).join('')}</div>`;
 if(tab==='learn')return tabs+`
 <p class="small muted" style="padding:0 2px">Short, practical notes on managing money, written for life in Africa.</p>
 <div class="stack">${LESSONS.map(x=>`<details class="card lesson" ${S.ui.lesson===x.id?'open':''} data-lesson="${x.id}"><summary><span class="chip" style="--c:var(--accent)">${ic(x.ic)}</span><span class="grow"><b style="font-size:14.5px">${x.t}</b><span class="xs muted" style="display:block">${x.min} min read${(S.read||[]).includes(x.id)?' · read':''}</span></span>${(S.read||[]).includes(x.id)?`<span class="pill good">${ic('check',12)}</span>`:''}</summary><div class="body">${x.b}<button class="btn sm" data-act="lessonDone" data-arg="${x.id}">${(S.read||[]).includes(x.id)?'Read':'Mark as read · +10 points'}</button></div></details>`).join('')}</div>
 <div class="sec-head"><h2>Books worth reading</h2></div>
 <div class="list">${BOOKS.map(([t,a,w])=>`<div class="setrow" style="align-items:flex-start"><span class="chip sm" style="--c:var(--warn)">${ic('book',18)}</span><span class="grow"><b>${t}</b><span>${a}</span><span style="margin-top:3px;color:var(--ink)">${w}</span></span></div>`).join('')}</div>
 <div class="sec-head"><h2>Free official resources</h2></div>
 <div class="list">${RESOURCES.map(([n,d,u])=>`<a class="setrow" href="${u}" target="_blank" rel="noopener" style="text-decoration:none;color:inherit"><span class="grow"><b>${n}</b><span>${d}</span></span>${ic('chev',16)}</a>`).join('')}</div>
 <p class="xs muted" style="padding:0 4px">General education, not regulated financial advice.</p>`;
 if(tab==='review'){const items=reviewItems();return tabs+`
 <div class="card stack" style="gap:6px"><b style="font-size:16px">Your personal review</b><p class="small muted">Built from your last 60 days on this phone. Nothing leaves the phone for this list.</p></div>
 ${items.map(x=>`<div class="card stack" style="gap:8px;border-left:4px solid var(--${x.k==='bad'?'bad':x.k==='warn'?'warn':x.k==='good'?'good':'accent'})"><b>${x.t}</b><p class="small">${x.b}</p>${x.a?`<button class="link small" style="align-self:flex-start" data-act="revAct" data-arg="${x.a[0]}">${x.a[1]} →</button>`:''}</div>`).join('')}
 ${aiOn()?`<button class="btn block primary" data-act="aiReview">${ic('sparkle')}Ask Claude for a deeper review</button><p class="xs muted" style="text-align:center">Sends only the anonymised summary. <button class="link xs" data-act="aiPayload">See it</button></p>`
  :`<div class="note">${ic('sparkle')}<span class="small">A deeper, Claude-written review is available for testing if you add your own Claude API key in Settings → Advisor.</span></div>`}
 <div id="aiOut"></div>`}
 return tabs+`
 <div class="note">${ic('shield')}<span class="small">${aiOn()?'Questions go to Claude with an anonymised summary only: totals by category, no names, numbers or individual transactions.':'Answers are worked out on this phone from your own figures. Nothing is sent anywhere.'} <button class="link small" data-act="aiPayload">See what's shared</button></span></div>
 <div class="chat" id="chat">${S.chat.map(m=>`<div class="msg ${m.me?'me':'ai'}">${m.html}</div>`).join('')}</div>
 <div class="chips" id="sugg">${['Am I on track this month?','What can I do to be better with money?','How much am I spending on boda per week?','Why did I run out of money last month?','How much did I spend on health?','I want to save 2 million by June','Should I buy T-bills or a fixed deposit?','What is a SACCO and is it worth joining?'].map(q=>`<button class="chipbtn" data-act="ask" data-arg="${esc(q)}">${q}</button>`).join('')}</div>
 <form class="composer" data-form="ask"><input id="askInput" name="q" placeholder="Ask about your money…" autocomplete="off" aria-label="Ask the advisor"><button class="send" aria-label="Send">${ic('send')}</button></form>`};
MOUNT.advisor=()=>{const v=$('#view');if((S.ui.adv||'ask')==='ask')v.scrollTop=v.scrollHeight;else if(S.ui.lesson){const d=document.querySelector(`[data-lesson="${S.ui.lesson}"]`);if(d)d.scrollIntoView({block:'start'});S.ui.lesson=null}};
ACT.advTab=k=>{S.ui.adv=k;refresh()};
ACT.lessonDone=id=>{S.read=[...new Set([...(S.read||[]),id])];if(window.gamePoints)gamePoints(10,'Read a lesson');if(window.gameBadge&&S.read.length>=3)gameBadge('learner');refresh()};
ACT.aiReview=async()=>{const box=$('#aiOut');box.innerHTML=`<div class="msg ai typing"><span></span><span></span><span></span></div>`;const r=await aiAsk('Review my finances and give me the 3 to 5 most useful things I can do in the next month to be better with money, starting with the most important.');
 const b=$('#aiOut');if(!b)return;b.innerHTML=r.ok?`<div class="card stack" style="gap:6px"><b>${ic('sparkle',16).replace('class="i"','class="i" style="display:inline;vertical-align:-2px;color:var(--accent)"')} Claude's review</b><div class="small">${mdLite(r.text)}</div></div>`:`<div class="note bad">${ic('alert')}<span class="small">${esc(r.status===401?'Your Claude API key was not accepted. Check it in Settings → Advisor.':'Claude could not be reached: '+r.text)}</span></div>`};
/* asking: Claude when switched on, otherwise on the phone */
const baseAdvise2=window.advise;
window.advise=function(q){const s=q.toLowerCase();
 if(isFresh()&&/better|improve|what can i do|advice|tips/.test(s)){const it=reviewItems().slice(0,4);return `Here's what stands out in your recent history:<ul>${it.map(x=>`<li><b>${x.t}.</b> ${x.b}</li>`).join('')}</ul>Open <b>My review</b> for the full list.`}
 if(isFresh()&&/health|medical|hospital|pharmacy/.test(s)&&/spen|cost|much/.test(s)){const l=expenses().filter(t=>t.cat==='health');return l.length?`You've spent <b>${ugx(sumAmt(l))}</b> on health this cycle:<ul>${groupSum(l,t=>subOf(t)||'Other').map(([n,v])=>`<li>${esc(n)}: ${ugx(v)}</li>`).join('')}</ul>`:'No health spending logged this cycle.'}
 return baseAdvise2(q)};
ask=function(q){if(!q.trim())return;pushChat(true,esc(q));if(cur()!=='advisor'){S.ui.adv='ask';go('advisor')}else refresh();
 const chat=$('#chat');if(chat)chat.insertAdjacentHTML('beforeend',`<div class="msg ai typing" id="typing"><span></span><span></span><span></span></div>`);$('#view').scrollTop=$('#view').scrollHeight;
 if(aiOn()){aiAsk(q).then(r=>{pushChat(false,r.ok?mdLite(r.text):`${advise(q)}<span class="meta">Claude couldn't be reached, so this answer was worked out on the phone.</span>`);if(cur()==='advisor'){refresh();$('#view').scrollTop=$('#view').scrollHeight}});return}
 setTimeout(()=>{pushChat(false,advise(q));if(cur()==='advisor'){refresh();$('#view').scrollTop=$('#view').scrollHeight}},650)};
ACT.ask=a=>ask(a);ACT.askAdvisor=a=>{S.ui.adv='ask';ask(a)};
FORMS.ask=(fd,f)=>{const q=fd.get('q');f.reset();ask(q)};
ACT.aiPayload=()=>openSheet('What the advisor would receive',`<p class="small muted" style="margin-bottom:8px">${aiOn()?'This summary is sent with each question to Claude.':'Nothing is sent now. This is what a Claude-powered advisor would receive.'} No names, phone numbers, merchants or individual transactions.</p><pre class="mono" style="margin:0">${esc(JSON.stringify(financeSummary(),null,2))}</pre>`);
