/* ===== Build 3 · family and household money (on one phone for now) ===== */
TITLES.family='Family & household';
const famSpent=(id,list)=>sumAmt((list||expenses()).filter(t=>(t.for||'me')===id));
const memberRow=(m,i)=>`<div class="hhm" style="display:grid;grid-template-columns:1fr 120px 34px;gap:8px;align-items:center"><input name="mname" value="${esc(m.name||'')}" placeholder="Name" aria-label="Member name" class="input" style="min-height:42px"><select name="mrole" class="input" style="min-height:42px" aria-label="Role"><option value="adult" ${m.role!=='child'?'selected':''}>Adult</option><option value="child" ${m.role==='child'?'selected':''}>Child</option></select><button type="button" class="icon-btn" style="width:34px;height:34px;border:0;background:none" data-act="hhRm" aria-label="Remove">${ic('x',16)}</button></div>`;
const householdForm=(hh,inOnb)=>{hh=hh||{name:(S.user&&S.user.name?S.user.name+"'s household":'My household'),members:[{name:'',role:'adult'}],familyBudget:''};
 return `<form class="stack" data-form="${inOnb?'onbFamily':'household'}">
  <label class="field"><span>Household name</span><input name="hname" value="${esc(hh.name)}" required></label>
  <div class="field"><span>Who else is in the household?</span><div class="stack" id="hhMembers" style="gap:6px">${hh.members.filter(m=>!m.me).map(memberRow).join('')||memberRow({role:'adult'})}</div><button type="button" class="link small" style="align-self:flex-start" data-act="hhAdd">+ Add a person</button><span class="xs muted">Add your partner, children and anyone whose costs you cover. Children get an allowance tracker.</span></div>
  <label class="field"><span>Monthly household budget (optional)</span><input name="fbudget" type="number" inputmode="decimal" step="any" value="${hh.familyBudget||''}" placeholder="0"></label>
  <button class="btn primary">${inOnb?'Continue':S.household?'Save household':'Set up household'}</button>
  ${inOnb?'<button type="button" class="btn" data-act="onbNextStep" data-arg="done" style="background:transparent">Skip, do this later</button>':''}</form>`};
ACT.hhAdd=()=>{$('#hhMembers').insertAdjacentHTML('beforeend',memberRow({role:'adult'}))};
ACT.hhRm=(a,el)=>{el.closest('.hhm').remove()};
function readHousehold(f){const names=[...f.querySelectorAll('[name=mname]')].map(x=>x.value.trim()),roles=[...f.querySelectorAll('[name=mrole]')].map(x=>x.value);const old=S.household?S.household.members:[];
 const members=[{id:(old.find(m=>m.me)||{}).id||'m0',name:(S.user&&S.user.name)||'Me',role:'adult',me:true}];
 names.forEach((n,i)=>{if(!n)return;const prev=old.find(m=>!m.me&&m.name===n);members.push({...(prev||{}),id:prev?prev.id:nid('m'),name:n,role:roles[i]||'adult'})});
 return{name:f.querySelector('[name=hname]').value.trim()||'My household',members,familyBudget:+f.querySelector('[name=fbudget]').value||0}}
FORMS.household=(fd,f)=>{S.household=readHousehold(f);closeSheet();refresh();toast('Household saved')};
ACT.editHousehold=()=>openSheet(S.household?'Edit household':'Set up your household',householdForm(S.household));
SCREENS.family=()=>{const hh=S.household;
 if(!hh)return `<div class="card stack" style="gap:12px"><span class="chip" style="--c:var(--accent);width:52px;height:52px">${ic('people',26)}</span><b style="font-size:18px">Manage money as a household</b><p class="small muted">Add the people you share costs with. Every expense can then be marked as yours, the household's, or for a particular person, and Kasente shows each side separately.</p><button class="btn primary" data-act="editHousehold">${ic('plus')}Set up your household</button></div>
  <div class="note">${ic('info')}<span class="small">For now the household lives on one phone. Each member using Kasente on their own phone, with shared data, comes with online sync in the next phase.</span></div>`;
 const list=expenses();const famT=sumAmt(list.filter(isFamilyTx)),meT=famSpent('me',list);const fb=hh.familyBudget;
 const kids=hh.members.filter(m=>m.role==='child');const shared=S.bills.filter(b=>b.shared&&b.status!=='paid');const hg=S.goals.filter(g=>g.family);
 return `
 <div class="card stack" style="gap:12px"><div class="between"><div><span class="eyebrow">Household</span><h2 style="font-size:20px;margin-top:2px">${esc(hh.name)}</h2></div><div class="row" style="gap:0">${hh.members.slice(0,5).map((m,i)=>`<span class="avatar" style="margin-left:${i?-10:0}px;border:2px solid var(--surface);${m.role==='child'?'background:var(--sun-soft);color:var(--warn)':''}">${initials(m.name)}</span>`).join('')}</div></div>
  <div class="stat3"><div class="stat" style="background:var(--bg)"><span>Household</span><b>${kf(famT)}</b></div><div class="stat" style="background:var(--bg)"><span>Personal</span><b>${kf(meT)}</b></div><div class="stat" style="background:var(--bg)"><span>Members</span><b>${hh.members.length}</b></div></div>
  ${fb?`<div class="stack" style="gap:5px"><div class="between small"><span>Household budget · ${cycleLabel()}</span><b class="tnum">${num(famT)} / ${num(fb)}</b></div><div class="bar thick"><i style="width:${Math.min(100,famT/fb*100)}%;background:${barColor(status(famT/fb))}"></i><span class="pace" style="left:${DAY_OF_CYCLE/CYCLE_DAYS*100}%"></span></div></div>`:`<button class="link small" style="align-self:flex-start" data-act="editHousehold">Set a household budget →</button>`}
  <div class="row"><button class="btn sm grow" data-act="add">${ic('plus',16)}Log household expense</button><button class="btn sm grow" data-act="shareFamily">${ic('send',16)}Share summary</button></div></div>
 <div class="sec-head"><h2>Where household money went</h2><button class="link" data-act="famSpending">Details</button></div>
 <div class="card stack" style="gap:8px">${famT?groupSum(list.filter(isFamilyTx),t=>t.cat).slice(0,6).map(([id,v])=>`<div class="stack" style="gap:3px"><div class="between small"><span>${(cat(id)||{}).name||id}</span><span class="tnum">${num(v)}</span></div><div class="bar" style="height:6px"><i style="width:${v/famT*100}%;background:${(cat(id)||{}).c||'var(--accent)'}"></i></div></div>`).join(''):'<p class="small muted">No household expenses yet this cycle. When you log an expense, choose "The household" or a person under "For".</p>'}</div>
 <div class="sec-head"><h2>Members</h2><button class="link" data-act="editHousehold">Edit</button></div>
 <div class="list">${hh.members.map(m=>`<div class="tx" style="grid-template-columns:40px 1fr auto"><span class="avatar" style="${m.role==='child'?'background:var(--sun-soft);color:var(--warn)':''}">${initials(m.name)}</span><span class="tx-main"><span class="tx-title">${esc(m.name)}${m.me?' (you)':''}</span><span class="tx-sub">${m.role==='child'?'Child':'Adult'}${m.note?' · '+esc(m.note):''}</span></span><span class="tx-amt">${kf(m.me?meT:famSpent(m.id,list))}<small>this cycle</small></span></div>`).join('')}</div>
 ${kids.length?`<div class="sec-head"><h2>Children</h2></div>${kids.map(k=>{const given=sumAmt(list.filter(t=>t.for===k.id&&t.sub==='Children'&&/allowance|pocket/i.test(t.title)));const spentK=famSpent(k.id,list);const subs=groupSum(list.filter(t=>t.for===k.id),t=>subOf(t)||(cat(t.cat)||{}).name);
  return `<div class="card stack" style="gap:10px"><div class="between"><b>${esc(k.name)}</b><button class="link small" data-act="kidEdit" data-arg="${k.id}">Allowance</button></div>
  ${k.allowance?`<div class="stack" style="gap:5px"><div class="between small"><span>Allowance given this cycle</span><b class="tnum">${num(given)} / ${num(k.allowance)}</b></div><div class="bar"><i style="width:${Math.min(100,given/k.allowance*100)}%;background:var(--sun)"></i></div></div>`:'<p class="xs muted">No allowance set.</p>'}
  <div class="between small"><span>Everything spent on ${esc(k.name)}</span><b class="tnum">${num(spentK)}</b></div>${subs.slice(0,4).map(([n,v])=>`<div class="between xs muted"><span>${esc(n)}</span><span class="tnum">${num(v)}</span></div>`).join('')}
  <button class="btn sm" data-act="giveAllowance" data-arg="${k.id}">${ic('coins',16)}Give allowance</button></div>`}).join('')}`:''}
 <div class="sec-head"><h2>Shared bills</h2><button class="link" data-go="bills">All bills</button></div>
 ${shared.length?`<div class="list">${shared.map(billRow).join('')}</div>`:'<div class="card small muted">Open any bill and switch on "Shared with household" to list it here.</div>'}
 <div class="sec-head"><h2>Household goals</h2><button class="link" data-act="famGoal">New goal</button></div>
 ${hg.length?hg.map(g=>`<div class="card stack" style="gap:8px"><div class="between"><b>${esc(g.name)}</b><span class="small muted tnum">${kf(g.saved)} / ${kf(g.target)}</span></div><div class="bar thick"><i style="width:${g.saved/g.target*100}%;background:var(--sun)"></i></div><button class="link small" style="align-self:flex-start" data-act="contrib" data-arg="${g.id}">Add money →</button></div>`).join(''):'<div class="card small muted">Save together for school fees, a holiday home visit or a family event.</div>'}
 <div class="note">${ic('info')}<span class="small">Right now the household lives on this phone. Members using Kasente on their own phones with the same shared data comes in the next phase with online sync. Until then, use "Share summary" to send the household picture on WhatsApp.</span></div>`};
ACT.famSpending=()=>{S.ui.spScope='family';go('spending')};
ACT.kidEdit=id=>{const k=S.household.members.find(m=>m.id===id);openSheet(`${esc(k.name)}'s allowance`,`<form class="stack" data-form="kid" data-id="${id}"><label class="field"><span>Allowance per month (${CUR()})</span><input name="allowance" type="number" inputmode="decimal" step="any" value="${k.allowance||''}"></label><label class="field"><span>Note (school, class…)</span><input name="note" value="${esc(k.note||'')}"></label><button class="btn primary">Save</button></form>`)};
FORMS.kid=(fd,f)=>{const k=S.household.members.find(m=>m.id===f.dataset.id);k.allowance=+fd.get('allowance')||0;k.note=fd.get('note').trim();closeSheet();refresh()};
ACT.giveAllowance=id=>{const k=S.household.members.find(m=>m.id===id);openSheet(`Allowance for ${esc(k.name)}`,`<form class="stack" data-form="giveAllowance" data-id="${id}"><label class="field"><span>Amount</span><input name="amt" type="number" inputmode="decimal" step="any" value="${k.allowance||''}" required></label><label class="field"><span>From</span><select name="acct">${acctOptions((S.accounts.find(a=>a.kind==='momo')||S.accounts[0]||{}).id)}</select></label><button class="btn primary">Record allowance</button></form>`)};
FORMS.giveAllowance=(fd,f)=>{const k=S.household.members.find(m=>m.id===f.dataset.id);addTxn({acct:fd.get('acct'),kind:'out',amt:+fd.get('amt'),cat:'family',sub:'Children',for:k.id,title:`Allowance · ${k.name}`,src:'manual'});closeSheet();refresh()};
ACT.famGoal=()=>{openGoal();setTimeout(()=>{const f=document.querySelector('[data-form=addGoal]');if(f)f.insertAdjacentHTML('beforeend','<input type="hidden" name="family" value="1">')},30)};
const baseGoalForm2=FORMS.addGoal;FORMS.addGoal=(fd,f)=>{baseGoalForm2(fd,f);if(fd.get('family')){const g=S.goals[S.goals.length-1];if(g)g.family=true;refresh()}};
ACT.shareFamily=()=>{const hh=S.household;const list=expenses();const famT=sumAmt(list.filter(isFamilyTx));
 const text=`${hh.name} · ${cycleLabel()}\nHousehold spending: ${ugx(famT)}${hh.familyBudget?` of ${ugx(hh.familyBudget)} budget`:''}\n\n`+groupSum(list.filter(isFamilyTx),t=>(cat(t.cat)||{}).name).map(([n,v])=>`• ${n}: ${ugx(v)}`).join('\n')+
  (S.bills.filter(b=>b.shared&&b.status!=='paid').length?`\n\nBills coming up:\n`+S.bills.filter(b=>b.shared&&b.status!=='paid').sort((a,b)=>a.due.localeCompare(b.due)).slice(0,6).map(b=>`• ${b.name}: ${ugx(b.amt)} by ${dlabel(b.due)}`).join('\n'):'')+`\n\nSent from Kasente`;
 if(NATIVE&&NATIVE.share){try{NATIVE.share(text,'Household summary');return}catch(e){}}saveOut('household-summary.txt','text/plain',text)};
/* shared switch on each bill */
const baseBill=ACT.bill;ACT.bill=id=>{baseBill(id);const b=S.bills.find(x=>x.id===id);const box=document.querySelector('.sheet-body .stack');if(box&&S.household)box.insertAdjacentHTML('afterbegin',`<div class="setrow" style="padding:4px 0;border:0"><span class="grow"><b>Shared with household</b><span>Shows on the family screen</span></span><button class="toggle ${b.shared?'on':''}" data-act="billShared" data-arg="${id}" aria-pressed="${!!b.shared}" aria-label="Shared with household"></button></div>`)};
ACT.billShared=(id,el)=>{const b=S.bills.find(x=>x.id===id);b.shared=!b.shared;el.classList.toggle('on',b.shared);save()};
